apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.namePrefix }}-pdb
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.namePrefix }}
